import React from "react";
import { UploadCloud, BrainCircuit, MessageSquare } from "lucide-react";
import { motion } from "framer-motion";

export default function HowItWorks() {
  const steps = [
    {
      icon: UploadCloud,
      title: "1. Upload Syllabus",
      desc: "Drop your PDF or DOCX. Our AI instantly reads and understands your curriculum.",
    },
    {
      icon: BrainCircuit,
      title: "2. Generate Plan",
      desc: "A personalised weekly plan built around your pace, goals, and exam date.",
    },
    {
      icon: MessageSquare,
      title: "3. Start Learning",
      desc: "Chat, speak, or explore diagrams generated by your AI Tutor in real time.",
    },
  ];

  const stepVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: (i) => ({
      opacity: 1,
      y: 0,
      transition: { delay: i * 0.18, duration: 0.55, ease: "easeOut" },
    }),
  };

  return (
    <section
      id="how-it-works"
      className="relative w-full py-24 text-white overflow-hidden"
    >
      {/* ❗ Removed internal glow so background matches the landing page */}
      {/* ❗ No grids, no bg colors — clean & unified */}

      <div className="max-w-7xl mx-auto px-6 relative z-10">
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-5xl font-bold leading-tight mb-4">
            From Syllabus to Success <br />
            <span className="bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
              in 3 Simple Steps
            </span>
          </h2>
          <p className="text-slate-400 text-sm max-w-xl mx-auto">
            No complex setup. No confusing features. Just upload and start
            learning.
          </p>
        </div>

        {/* Steps Grid */}
        <div className="relative grid grid-cols-1 md:grid-cols-3 gap-14">
          {/* Connecting dashed line */}
          <div className="hidden md:block absolute top-[65px] left-[12%] right-[12%] h-0.5 border-t border-dashed border-white/20" />

          {steps.map((step, i) => (
            <motion.div
              key={i}
              custom={i}
              variants={stepVariants}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true }}
              className="relative flex flex-col items-center text-center"
            >
              {/* Icon container */}
              <motion.div
                whileHover={{ scale: 1.1 }}
                transition={{ duration: 0.25 }}
                className="w-24 h-24 rounded-full bg-black/40 border border-white/10 flex items-center justify-center mb-6 shadow-[0_0_35px_rgba(0,0,0,0.5)] backdrop-blur-xl relative"
              >
                <step.icon size={36} className="text-purple-300" />
              </motion.div>

              {/* Title */}
              <h3 className="text-xl font-semibold mb-2">{step.title}</h3>

              {/* Description */}
              <p className="text-slate-400 text-sm max-w-xs leading-relaxed">
                {step.desc}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
