import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import Sidebar from "../components/Sidebar";
import axios from "axios";
import { useAuth } from "../Context/AuthContext";
import { motion } from "framer-motion";
import { Loader2 } from "lucide-react";

export default function ViewStudyPlan() {
  const { id } = useParams();
  const { token } = useAuth();
  const API = import.meta.env.VITE_API_URL;

  const [plan, setPlan] = useState(null);
  const [loading, setLoading] = useState(true);

  // Fetch Plan
  useEffect(() => {
    axios
      .get(`${API}/studyplan/${id}`, {
        headers: { Authorization: `Bearer ${token}` },
      })
      .then((res) => {
        setPlan(res.data.plan);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [id, token]);

  // Loading Screen
  if (loading)
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#020617] text-white">
        <Loader2 className="animate-spin" size={40} />
      </div>
    );

  if (!plan)
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#020617] text-white">
        <p className="text-slate-400">No study plan found.</p>
      </div>
    );

  // Format AI text into paragraphs
  const formattedText = plan.planText
    .split("\n")
    .filter((line) => line.trim().length > 0);

  return (
    <div className="min-h-screen flex bg-[#020617] text-white">
      <Sidebar />

      <motion.div
        initial={{ opacity: 0, y: 18 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex-1 p-6 md:p-10 overflow-y-auto"
      >
        {/* Page Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-semibold bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">
            Study Plan Overview
          </h1>
          <p className="text-slate-400 mt-1">
            Your personalised learning roadmap.
          </p>
        </div>

        {/* Study Plan Card */}
        <div className="bg-white/[0.05] border border-white/10 rounded-3xl p-8 backdrop-blur-xl shadow-[0_0_70px_rgba(0,0,0,0.7)]">
          {formattedText.map((line, idx) => {
            const isHeading =
              line.toLowerCase().includes("day") ||
              line.toLowerCase().includes("week") ||
              line.endsWith(":");

            return (
              <motion.p
                key={idx}
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.02 }}
                className={`mb-4 whitespace-pre-wrap leading-relaxed ${
                  isHeading
                    ? "text-purple-300 font-semibold text-lg mt-4"
                    : "text-slate-300"
                }`}
              >
                {line}
              </motion.p>
            );
          })}
        </div>

        <div className="mt-6 text-center text-slate-500 text-xs">
          Generated by Brofessor.AI — Smart Study Assistant 📘✨
        </div>
      </motion.div>
    </div>
  );
}
